# Generated by Django 5.2.4 on 2025-07-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Link', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=100)),
            ],
        ),
    ]
